# Generated by Django 4.1.5 on 2023-04-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meme',
        ),
    ]
